#!/usr/bin/python3

import sys

if len(sys.argv) < 2:
    sys.exit(1)
    
def factorize(n):
    for i in range(2, n):
        if n % i == 0:
            return i, n // i
        
with open(sys.argv[1], 'r') as file:
    for line in file:
        n = int(line)
        p, q = factorize(n)
        print(f"{n}={p} * {q}")
